### ISSUE TITLE
RunTime Error 

### ISSUE THREAD

**Issue by alrashadlewis** [emanuelez/PySynergy#11]
Hello,

I am in need of assistance. I am using PYSynergy to migrate my Synergy project, used in Rational Synergy 7.2, to Git. I am currently using Python version 2.6.6 running on Red Hat Enterprise Linux 6.2 (Santiago). After running 'get_synergy_history.py', I get the following Exception and stack trace:

Offline mode, just using cache
Offline mode, just using cache
Offline mode, just using cache
Offline mode, just using cache
Offline mode, just using cache
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib64/python2.6/multiprocessing/pool.py", line 281, in _handle_results
    task = get()
TypeError: ('__init__() takes exactly 2 arguments (1 given)', <class 'SynergySession.SynergyException'>, ())

Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x15375d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x15375d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x15375d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x15375d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x15375d0>> ignored
Exception AssertionError: AssertionError() in <Finalize object, dead> ignored
Traceback (most recent call last):
  File "get_synergy_history.py", line 93, in <module>
    main()
  File "get_synergy_history.py", line 81, in main
    history = ccm_hist.get_project_history(config['master'], config['base_project'])
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/CCMHistory.py", line 58, in get_project_history
    release_chain = deque(get_project_chain(latest_project, base_project, self.ccm))
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/CCMHistory.py", line 538, in get_project_chain
    baseline = ccm_cache.get_object(head_project, ccm)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_cache.py", line 86, in get_object
    raise ObjectCacheException("Couldn't extract %s from Synergy" % obj)
ccm_cache.ObjectCacheException: "Couldn't extract msw-msw_v9.0.0:project:a#1 from Synergy"

If anyone is available to assist me in troubleshooting this issue, I would most certainly appreciate it.

**Comment by dvaske** [comment]
You were always running in offline mode, try this fix.

**Comment by alrashadlewis** [comment]
Hello again,

Thank you for pushing the fix. I switched the offline option to true as suggested, and I tried to run get_synergy_history.py, and I get the following stack trace:

Traceback (most recent call last):
  File "get_synergy_history.py", line 93, in <module>
    main()
  File "get_synergy_history.py", line 77, in main
    ccm, ccm_pool = start_sessions(config)
  File "get_synergy_history.py", line 35, in start_sessions
    ccm = SynergySession(config['database'], offline=config['offline'])
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/SynergySession.py", line 76, in **init**
    raise SynergyException('Error while starting a synergy Session: ' + stderr)
SynergySession.SynergyException: 'Error while starting a synergy Session: CRCCK2015E The username or password is not valid.\nRecommendation: Verify that server address, username, and password are correct. If the engine host is a Windows machine, then also check if ccm_ess is running.\n'
Exception KeyError: ('CCM_ADDR',) in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0xcf1050>> ignored

What is confusing about this issue is that if the username and/or password were invalid, then I would not be able to start Rational Synergy GUI application (which I currently can). The username 'ccm_root' was created as specified in the Rational Synergy 7.2.1 Installation and Configuration Guide, and the password was created using the Rational Directory Administration. What would you suggest?

**Comment by alrashadlewis** [comment]
Hello again,

I found a way around the aforementioned error. Unfortunately, I encounter a new problem. The stack trace is below.

^CTraceback (most recent call last):
  File "get_synergy_history.py", line 93, in <module>
    main()
  File "get_synergy_history.py", line 81, in main
    history = ccm_hist.get_project_history(config['master'], config['base_project'])
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/CCMHistory.py", line 78, in get_project_history
    self.find_project_diff(baseline_project, None)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/CCMHistory.py", line 209, in find_project_diff
    object = ccm_cache.get_object(o, self.ccm)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_cache.py", line 85, in get_object
    object_data = get_object_from_ccm(obj, ccm, ccm_cache_path)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_cache.py", line 306, in get_object_from_ccm
    object = create_file_or_dir_object(synergy_object, ccm)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_cache.py", line 245, in create_file_or_dir_object
    object.releases = get_releases(synergy_object, ccm)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_cache.py", line 450, in get_releases
    res = ccm.query("has_member('{0}') and status='released'".format(object.get_object_name())).format('%objectname').run()
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/SynergySession.py", line 322, in run
    result = self._run(command)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/SynergySession.py", line 139, in _run
    stdout, stderr = p.communicate()
  File "/usr/lib64/python2.6/subprocess.py", line 729, in communicate
    stdout, stderr = self._communicate(input, endtime)
  File "/usr/lib64/python2.6/subprocess.py", line 1310, in _communicate
    stdout, stderr = self._communicate_with_poll(input, endtime)
  File "/usr/lib64/python2.6/subprocess.py", line 1378, in _communicate_with_poll
    ready = poller.poll(self._remaining_time(endtime))
KeyboardInterrupt
Stopping mecore1toc.qa.gmsmail.com:43988:10.4.24.97
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7fc67b3d8290>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7fc67b3d8350>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7fc67b3d83d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7fc67b3d8550>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7fc67b3d8450>> ignored

The program is stuck in line 1378 of /usr/lib64/python2.6/subprocess.py. There is no clear error, and the stack trace is printed only after I send the interrupt signal.

**Comment by dvaske** [comment]
It seems to me that it is running, querying synergy and you terminate it with the interrupt signal.

**Comment by alrashadlewis** [comment]
That was it. The program was still running. But after about a few hours, the program terminated and raised a SynergyException.

Traceback (most recent call last):
  File "get_synergy_history.py", line 93, in <module>
    main()
  File "get_synergy_history.py", line 81, in main
    history = ccm_hist.get_project_history(config['master'], config['base_project'])
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/CCMHistory.py", line 155, in get_project_history
    ccm_types_perms = ccm_type.get_types_and_permissions(self.ccm)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/ccm_types.py", line 39, in get_types_and_permissions
    lines = ccm.attr(t.get_object_name()).option("-s").option("file_acs").run().splitlines()
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/SynergySession.py", line 322, in run
    result = self._run(command)
  File "/app/CMSynergy/ccm7.2/ccm_root/PySynergy-master/SynergySession.py", line 145, in _run
    raise SynergyException('Error while running the Synergy command: %s \nError message: %s' % (command, stderr))
SynergySession.SynergyException: "Error while running the Synergy command: ['ccm', 'attr', '-s', 'file_acs', 'acc_data~1:attype:AC'] \nError message: CRCCG1003E Attribute file_acs does not exist on the object AC/attype/acc_data/1.\n"
Stopping mecore1toc.qa.gmsmail.com:52151:10.4.24.97
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7f6691a491d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7f6691a49350>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7f6691a493d0>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7f6691a49090>> ignored
Exception SynergySession.SynergyException: SynergyException() in <bound method SynergySession.__del__ of <SynergySession.SynergySession object at 0x7f6691a49150>> ignored

Have you seen this before?

**Comment by dvaske** [comment]
Yeah, synergy is damn slow...
Lets take the rest in the email thread

**Comment by cbrownrt** [comment]
Can someone share the solution?  I'm getting the same error.

**Comment by StevenLooman** [comment]
I, too, am looking for the solution, @dvaske. Please do share it.

**Comment by StevenLooman** [comment]
For anybody who comes after me, I simply skipped this loop.

Additionally, when trying to get permissions for file types (at several places in `ccm_fast_export.py`), I chose a default (of '100664') if the file type could not be found.

Hope this helps anybody.
