### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by cbrownrt** [emanuelez/PySynergy#12]
What version of Python and Rational Synergy was this code designed to work with?

I am running with Python 2.7.10 (3.5 did not work at all) and Synergy 7.2.0.6 and CCM.exe crashes in what appears to be every time it is called.

**Comment by dvaske** [comment]
Python 2.7, ccm 6.x

However, I know several cases where ccm 7.1 or 7.2 was used.

**Comment by cbrownrt** [comment]
It's working now.  I had a login issue and removed -q from the ccm start, which caused it to output WAAAY too much instead of just the instance data.

**Comment by dvaske** [comment]
Cool, let me know if you have other problems. I might be able to help.
